require 'fileutils'
require 'rake/clean'

CPP_COMPILER = "g++"
CPP_COMPILER_FLAGS = "-std=c++11 -fprofile-arcs -ftest-coverage"
INCLUDE_DIR = "../include"
SOURCES_DIR = "."
RELEASE_DIR = ""
SOURCES = FileList["#{SOURCES_DIR}/*.cpp"]
OBJECTS = SOURCES.ext('o')
TARGET_NAME = "test_atestcov"
CPP_LD_FLAGS = "-lgtest -Wall -fprofile-arcs -ftest-coverage"

CLEAN.include(["#{SOURCES_DIR}/*.o", "*.exe"])

if /windows/i =~ ENV['OS'] then
    TARGET = "#{TARGET_NAME}.exe"
else
    TARGET = "#{TARGET_NAME}"
end

task :default => :build
task :all => [:build]
task :rebuild => ["clean", :test]

desc "run test"
task :test => OBJECTS do |t|
  sh "#{CPP_COMPILER} -o #{TARGET} #{t.prerequisites.join(' ')} #{CPP_LD_FLAGS}"
  sh "./#{TARGET}"
end

rule '.o' => '.cpp' do |t|
  sh "#{CPP_COMPILER} -I #{INCLUDE_DIR} -c #{t.source} -o #{t.name} #{CPP_COMPILER_FLAGS}"
end
